# Generated by Django 5.2.11 on 2026-02-13 09:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('return_percent', models.DecimalField(decimal_places=2, default=5, max_digits=5)),
                ('terms', models.TextField(default='Minimum investment ₹5000, guaranteed return 5% for 1 year')),
                ('date_invested', models.DateTimeField(default=django.utils.timezone.now)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_investments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
