# Generated by Django 5.2.11 on 2026-02-13 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_investment'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='agreement_pdf',
            field=models.FileField(blank=True, upload_to='investment_agreements/'),
        ),
    ]
